=== zhanmenaz/candy/src/test/java/Candy.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="Ingridient">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="amount" type="xs:positiveInteger" use="required"/>
                <xs:attribute name="unit" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="Value">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="amount" type="xs:positiveInteger" use="required"/>
                <xs:attribute name="unit" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="CandyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="chocolate"/>
            <xs:enumeration value="sweet"/>
            <xs:enumeration value="waffel"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ChocolateType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="white">
            <xs:enumeration value="black">
            <xs:enumeration value="milk">
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Candy">
        <xs:sequence>
            <xs:element name="CandyInstance" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Ingridient" type="Ingridient"/>
                        <xs:element name="Ingridient" type="Ingridient"/>
                        <xs:element name="Ingridient" type="Ingridient"/>
                        <xs:element name="Value" type="Value"/>
                        <xs:element name="Value" type="Value"/>
                        <xs:element name="Value" type="Value"/>
                        <xs:element name="Production" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:integer" use="required"/>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="energy" type="xs:string" use="required"/>
                    <xs:attribute name="type" type="CandyType" use="required"/>
                    <xs:attribute name="chocolate" type="ChocolateType" use="required"/>
                    <xs:attribute name="water" type="xs:boolean" use="optional"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="Candy" type="Candy"/>
</xs:schema>

=== zhanmenaz/candy/src/test/java/com/epam/zhanassyl/task3/OutputXML.xml
<?xml version = "1.0" encoding="ISO-8859-1"?>
<Candy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="Candy.xsd">
    <CandyInstance id="0" name="Bayan-sulu" energy="9500" type="chocolate" water="true" chocolate="white" >
        <Ingridient amount="1" unit="milligram">Sugar</Ingridient>
        <Ingridient amount="10" unit="milligram">Fructose</Ingridient>
        <Ingridient amount="1" unit="milligrams">Vanilin</Ingridient>
        <Value amount="3" unit="grams">Protein</Value>
        <Value amount="4" unit="grams">Fat</Value>
        <Value amount="5" unit="grams">Carbohydrate</Value>
        <Production>FirmA</Production>
    </CandyInstance>


    <CandyInstance id="1" name="Rahat" energy="10000" type="chocolate" water="true" chocolate="black" >
        <Ingridient amount="2" unit="milligram">Sugar</Ingridient>
        <Ingridient amount="20" unit="milligram">Fructose</Ingridient>
        <Ingridient amount="2" unit="milligram">Vanilin</Ingridient>
        <Value amount="1" unit="grams">Protein</Value>
        <Value amount="2" unit="grams">Fat</Value>
        <Value amount="3" unit="grams">Carbohydrate</Value>
        <Production>FirmA</Production>
    </CandyInstance>
</Candy>
